# Generated by Django 4.2.2 on 2023-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_funcionario_alter_recibo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='arquivo',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
    ]
