# Generated by Django 4.2.2 on 2024-01-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_recibo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='arquivo',
            field=models.CharField(max_length=500, verbose_name='nome'),
        ),
    ]
