# Generated by Django 4.2.2 on 2023-07-14 19:30

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_arquivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=menu.models.case_upload_location),
        ),
    ]
