# Generated by Django 4.2.2 on 2023-07-14 19:41

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_arquivo_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('number_folder', models.CharField(max_length=250, verbose_name='Numero de Carpeta')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='arquivo_pdf',
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=menu.models.case_upload_location)),
                ('sub_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.case')),
            ],
        ),
    ]
