# Generated by Django 4.2.2 on 2023-07-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_case_remove_menu_arquivo_pdf_casefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casefile',
            old_name='sub_menu_id',
            new_name='case',
        ),
    ]
