# Generated by Django 4.2.2 on 2023-07-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_rename_sub_menu_id_casefile_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casefile',
            old_name='case',
            new_name='name',
        ),
    ]
